
# PROMPT configuriation - begin
source ~/.git-completition.bash
source ~/.git-prompt.sh
source .bash_prompt

PATH=/usr/local/bin:$PATH

alias l='ls -aG'
alias ls='ls -G'
alias bitcoin-inst='cd /Users/david/Library/Application\ Support/Bitcoin/'

